apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project }}-config
  labels:
    app: {{ .Release.Name }}
data:
{{- range $key, $value := .Values.config }}
  {{- $cmKeyName := (regexReplaceAllLiteral "Tpl$" $key "") -}}
  {{- include "renderOptionalYamlOrTpl" (dict "context" $ "values" $.Values.config "key" $cmKeyName) | indent 2 -}}
{{ end }}
