apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets -}}
  {{- $secretName := (regexReplaceAllLiteral "Tpl$" $key "") -}}
  {{- $validatedValue := required (printf "Value for secret %s is undefined" $key) $value }}
  {{ default $secretName | quote }}: {{ include "renderOptionalYamlOrTpl" (dict "context" $ "values" $.Values.secrets "key" $secretName "skipParent" true) | b64enc | quote -}}
{{- end -}}
